FORMAT: 1A
HOST: http://www.beerbanana.cz/beerbanana/

# BeerBanana

TODO description

# Terminology

## Drinker
`DRINKER` is a person who has an account (registration) and who consumes drinks 
of various types.

##### Properties
| name             | type            | mandatory | description
|------------------|-----------------|-----------|------------
| id               | number          | yes       | drinker identifier
| firstName        | string          | yes       | first name identifier
| lastName         | string          | yes       | last name identifier
| nickName         | string          | no        | random nick name provided by drinker
| email            | string          | yes       | drinker email address
| status           | string          | yes       | drinker status, e.g. Sober, Tipsy, Drunk And Ravenous, Where The Hell Are My Keys, Jackson Pollock, Completely Smashed
| dateRegistration | string          | yes       | formatted [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date
| comment          | string          | no        | random information provided by drinker, editable at any time, max 500 chars
| consumedByUnits  | Consumed Units  | yes       | number of total drinks consumed by alcohol unit
| consumedByLitres | Consumed Litres | yes       | number of total alcohol consumed in litres


`DRINK TYPE` is describes a kind of beverage. It's characterized by name, volume,
alcohol content etc.

`CONSUMPTION` is the act of ingestion of one unit of a beverage by a DRINKER.


# Group Drinks

## Drinks Collection [/drinks{?title,percentage,drinkerId}]

### List All Drinks [GET]

Retrieves all drinks or by request parameters title, percentage and drinker identifier.

+ Parameters
    + title: `Staropramen` (string, optional) - official title or part of it. Case insensitive
    + percentage: `beer` (enum, optional) - alcohol percentage category, e.g. beer, wine, cocktail, shot, other. Case insensitive
    + drinkerId: `12345` (number, optional) - drinker identifier

+ Response 200 (application/json;charset=UTF-8)
    + Attributes (array[Drinks Collection Response])


## Single Drink [/drinks/{id}]

### Retrieve Drink [GET]

Retrieves drink object by its identifier.

+ Response 200 (application/json;charset=UTF-8)
    + Attributes (Drink Response)


# Data Structures

### Drink (object)
- id: `12345` (number, required) - drink identifier
- title: `Staropramen 11°` (string, required) - official drink title
- volume: `0.5` (number, required) - usual drink capacity in litres
- percentage: `4.7` (number, required) - alcohol percentage per usual drink capacity
- consumption: `1458` (number, required) - number of drinkers who consumed current drink

### Drinker (object)
- id: `22356` (number, required) - drinker identifier
- firstName: `Martin` (string, required) - first name identifier
- lastName: `Kašpar` (string, required) - last name identifier
- nickName: `Mkax` (string, optional) - random nick name provided by drinker
- email: `kaspar.mart@gmail.com` (string, required) - drinker email address
- status: `Completely Smashed` (string, required) - drinker status, e.g. Sober, Tipsy, Drunk And Ravenous, Where The Hell Are My Keys, Jackson Pollock, Completely Smashed
- dateRegistration: `14:52 February 27, 2017` (string, required) - formatted [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date
- comment: `lol, im batman!` (string, optional) - random information provided by drinker, editable at any time, max 500 chars
- totalConsumedByUnits (Drinks Consumed Units) 
- totalConsumedByLitres (Drinks Consumed Litres)

### Drinks Collection Response (object)
- Include Drink

### Drink Response (object)
- Include Drink
- drinkers (array[Drinker])

### Drinks Consumed Units(object)
- totalDrinks: `1124` (number, required) - number of total alcohol units consumed
- beers: `895` (number, required) - total beers consumed
- wines: `452` (number, required) - total wines consumed
- shots: `321` (number, required) - total shots consumed
- other: `89` (number, required) - total other drinks consumed

### Drinks Consumed Litres (object)
- totalAlcohol: `458.62` (number, required) - number of total alcohol consumed in litres
- beers: `421` (number, required) - total beers consumed in litres
- wines: `212` (number, required) - total wines consumed in litres
- shots: `162` (number, required) - total shots consumed in litres
- other: `56` (number, required) - total other drinks consumed in litres